series: Intermediate C++
title: C++ Reading Files
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Basic usage of fstream.
language: C++
tags:
  - Core
  - Input
extra_resources:
connections:
  - series: Basic C++
    title: C++ Console IO